### ISSUE TITLE
Replace the old regionInfo.dat with the new one

### ISSUE THREAD

**Issue by MatadorProBr** [barkermn01/Skeld.Net-Launcher#1]
When I used the launcher to play on skeld.net, it gave this error.
![image](https://user-images.githubusercontent.com/71022656/103153607-7c2a7a80-4770-11eb-8535-c4785da32fb2.png)

So I went to the site and realized that they replaced it with a new server, that is, this regionInfo.dat is no longer working, so you have to put the new one.

**Comment by barkermn01** [comment]
This has been fixed and new setups have been draft released. if you could test @MatadorProBr

**Comment by MatadorProBr** [comment]
> This has been fixed and new setups have been draft released. if you could test @MatadorProBr

![image](https://user-images.githubusercontent.com/71022656/103587725-a4c81800-4ec6-11eb-852d-0532f8625081.png)
The same error still remains.

**Comment by barkermn01** [comment]
strange... i will look into it when i get time

**Comment by barkermn01** [comment]
So this is because the Skeld System has brought out its own launcher that also injects into the game as such these files are no longer obtainable for this to work.
